behaviors:
  MarsTaxi:
    trainer_type: ppo
    time_horizon: 64    # v1_2
    max_steps: 1e7
    hyperparameters:
      learning_rate: 1e-4 # v1_2
      batch_size: 2048
      buffer_size: 500000 # v1_2
      num_epoch: 3
    network_settings:
      normalize: true
      num_layers: 3
      hidden_units: 256
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
    summary_freq: 25000
    threaded: true
torch_settings:
  device: cpu