behaviors: # Módosított jutalom rendszer (3) (V3 kb 2,3 millioig tanult)
  MarsTaxi: # AddReward(0.005f * (originalDistance / distance) - (StepCount / 5000));
    trainer_type: ppo
    time_horizon: 64    # v1_2
    max_steps: 1e7
    hyperparameters:
      learning_rate: 3e-4 # teszt2: 3e-5
      batch_size: 2048 # v3
      buffer_size: 50000 # v1_3
      num_epoch: 3
    network_settings:
      normalize: true
      num_layers: 3
      hidden_units: 256
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
    summary_freq: 50000 # v2
    threaded: true
torch_settings:
  device: cpu